// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWfWSn-EeWLSlL8It6c-JkhsB3phIEiNY',
    appId: '1:821410252234:web:e72f27e31577cced25fb33',
    messagingSenderId: '821410252234',
    projectId: 'aaroha-saf',
    authDomain: 'aaroha-saf.firebaseapp.com',
    storageBucket: 'aaroha-saf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ7RmH5mdkRR5RPOT6ALu7F6bvRvLtWjg',
    appId: '1:821410252234:android:11ba78016c43494425fb33',
    messagingSenderId: '821410252234',
    projectId: 'aaroha-saf',
    storageBucket: 'aaroha-saf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdxEJROat11lO_s2EM3p9vTdBobwYQJqc',
    appId: '1:821410252234:ios:74b0ee33766076ce25fb33',
    messagingSenderId: '821410252234',
    projectId: 'aaroha-saf',
    storageBucket: 'aaroha-saf.firebasestorage.app',
    iosBundleId: 'com.example.aarohaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdxEJROat11lO_s2EM3p9vTdBobwYQJqc',
    appId: '1:821410252234:ios:74b0ee33766076ce25fb33',
    messagingSenderId: '821410252234',
    projectId: 'aaroha-saf',
    storageBucket: 'aaroha-saf.firebasestorage.app',
    iosBundleId: 'com.example.aarohaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWfWSn-EeWLSlL8It6c-JkhsB3phIEiNY',
    appId: '1:821410252234:web:43a557cf1c91a3d325fb33',
    messagingSenderId: '821410252234',
    projectId: 'aaroha-saf',
    authDomain: 'aaroha-saf.firebaseapp.com',
    storageBucket: 'aaroha-saf.firebasestorage.app',
  );

}